PROPERTY_ORDER = [
    "serviceQuality",
    "staffFriendliness",
    "foodQuality",
    "valueForMoney",
    "portionSatisfaction",
    "cleanliness",
    "speed",
    "ambience",
    "groupSuitability",
    "dateSuitability",
    "repeatVisitIntent",
    "viewQuality",
    "luxuryPerception",
    "reservationEase",
]


PROPERTY_DEFINITIONS = {
    "serviceQuality": {
        "displayName": "Service Quality",
        "description": "Overall quality and reliability of the service experience.",
        "positive": [
            "great service",
            "excellent service",
            "good service",
            "amazing service",
            "attentive service",
            "professional service",
            "service has been incredible",
            "five-star service",
            "gold standard of service",
            "exceptional hospitality",
            "warm hospitality",
        ],
        "negative": [
            "bad service",
            "terrible service",
            "poor service",
            "awful service",
            "unprofessional service",
            "unaware",
            "mistakenly seated",
            "left standing",
            "no apology",
            "proper apology",
        ],
    },
    "staffFriendliness": {
        "displayName": "Staff Friendliness",
        "description": "Warmth, politeness, and helpfulness of staff interactions.",
        "positive": [
            "friendly staff",
            "kind staff",
            "welcoming staff",
            "polite staff",
            "helpful staff",
            "courteous staff",
            "friendliness",
            "kind",
            "welcoming",
            "friendly conversation",
            "treated like family",
            "warmly introduced",
            "thoughtful care",
            "professionally",
        ],
        "negative": [
            "rude staff",
            "unfriendly staff",
            "cold staff",
            "impolite staff",
            "dismissive staff",
        ],
    },
    "foodQuality": {
        "displayName": "Food Quality",
        "description": "Taste, freshness, and overall quality of the food.",
        "positive": [
            "delicious",
            "tasty",
            "fresh",
            "very tasty",
            "excellent food",
            "amazing food",
            "quality food",
            "excellent quality",
            "outstanding meals",
            "food and drinks",
            "breakfast memorable",
            "ramadan buffet",
        ],
        "negative": [
            "bland",
            "tasteless",
            "stale",
            "bad food",
            "terrible food",
            "undercooked",
            "overcooked",
            "disappointing breakfast",
        ],
    },
    "valueForMoney": {
        "displayName": "Value For Money",
        "description": "Whether the price feels justified by the overall experience.",
        "positive": [
            "worth the price",
            "good value",
            "value for money",
            "worth every penny",
            "reasonably priced",
            "affordable",
        ],
        "negative": [
            "overpriced",
            "too expensive",
            "not worth the price",
            "poor value",
            "expensive for what it is",
        ],
    },
    "portionSatisfaction": {
        "displayName": "Portion Satisfaction",
        "description": "Satisfaction with portion size and fullness provided.",
        "positive": [
            "large portions",
            "generous portions",
            "big portions",
            "filling",
            "satisfying portion",
            "portion size was great",
        ],
        "negative": [
            "small portions",
            "tiny portions",
            "not filling",
            "portion size was small",
            "too little food",
        ],
    },
    "cleanliness": {
        "displayName": "Cleanliness",
        "description": "Perceived cleanliness of the restaurant and dining environment.",
        "positive": [
            "clean",
            "very clean",
            "spotless",
            "well kept",
            "hygienic",
            "clean environment",
        ],
        "negative": [
            "dirty",
            "unclean",
            "filthy",
            "messy",
            "not clean",
            "poor hygiene",
        ],
    },
    "speed": {
        "displayName": "Speed",
        "description": "How quickly food, service, or seating is provided.",
        "positive": [
            "fast service",
            "quick service",
            "served quickly",
            "came quickly",
            "prompt service",
            "didn't wait long",
            "always around",
        ],
        "negative": [
            "slow service",
            "very slow",
            "took too long",
            "long wait",
            "waited too long",
            "service was slow",
            "waited",
            "for quite some time",
            "left standing",
        ],
    },
    "ambience": {
        "displayName": "Ambience",
        "description": "Atmosphere, mood, and overall feel of the space.",
        "positive": [
            "nice atmosphere",
            "great atmosphere",
            "cozy",
            "beautiful ambience",
            "pleasant ambience",
            "lovely setting",
            "beautiful",
            "mesmerizing",
            "unforgettable experience",
            "breathtaking",
        ],
        "negative": [
            "bad atmosphere",
            "noisy",
            "too loud",
            "uncomfortable ambience",
            "boring atmosphere",
        ],
    },
    "groupSuitability": {
        "displayName": "Group Suitability",
        "description": "How suitable the restaurant feels for groups, families, or friends.",
        "positive": [
            "good for groups",
            "great for groups",
            "family dinner",
            "good for families",
            "good for friends",
            "spacious for groups",
        ],
        "negative": [
            "too small",
            "not good for groups",
            "not suitable for groups",
            "cramped for groups",
            "hard to sit together",
        ],
    },
    "dateSuitability": {
        "displayName": "Date Suitability",
        "description": "How appropriate the restaurant feels for a date or romantic outing.",
        "positive": [
            "great for a date",
            "perfect for a date",
            "romantic",
            "date night",
            "cozy for couples",
            "nice for couples",
        ],
        "negative": [
            "not good for a date",
            "not romantic",
            "too loud for a date",
            "awkward for couples",
            "bad date spot",
        ],
    },
    "repeatVisitIntent": {
        "displayName": "Repeat Visit Intent",
        "description": "Signals that customers want to come back again.",
        "positive": [
            "will come back",
            "would come again",
            "come back again",
            "visit again",
            "definitely return",
            "would return",
            "look forward to returning soon",
            "returning soon",
            "recommend this hotel to anyone",
            "highly recommend",
            "strongly recommend",
        ],
        "negative": [
            "won't come back",
            "would not come again",
            "never again",
            "not coming back",
            "wouldn't return",
        ],
    },
    "viewQuality": {
        "displayName": "View Quality",
        "description": "Quality and appeal of the restaurant's view or scenery.",
        "positive": [
            "great view",
            "amazing view",
            "beautiful view",
            "nice view",
            "lovely view",
            "sea view",
            "bosphorus view",
            "view room",
            "breathtaking view",
            "spectacular",
            "scenery was simply spectacular",
            "downtown istanbul",
        ],
        "negative": [
            "bad view",
            "no view",
            "ugly view",
            "view was disappointing",
            "blocked view",
        ],
    },
    "luxuryPerception": {
        "displayName": "Luxury Perception",
        "description": "Signals that the experience feels premium, upscale, or refined.",
        "positive": [
            "luxurious",
            "upscale",
            "premium",
            "high end",
            "elegant",
            "fine dining",
        ],
        "negative": [
            "cheap feel",
            "not upscale",
            "not luxurious",
            "low quality feel",
            "ordinary atmosphere",
        ],
    },
    "reservationEase": {
        "displayName": "Reservation Ease",
        "description": "How easy and smooth the reservation process feels.",
        "positive": [
            "easy to book",
            "easy reservation",
            "reservation was easy",
            "booked easily",
            "smooth reservation",
            "quick reservation",
        ],
        "negative": [
            "hard to book",
            "difficult reservation",
            "reservation was difficult",
            "couldn't book",
            "reservation problem",
            "booking was a hassle",
        ],
    },
}
